#!/usr/bin/env node
/**
 * Turns the raw Lighthouse JSON reports in a directory into a single Markdown
 * summary: one scores table per audited URL plus the biggest opportunities.
 *
 * Usage:
 *   node scripts/lighthouse-summary.mjs <reports-dir> [output.md]
 *
 * <reports-dir> is scanned for "*.report.json" files (the JSON output of the
 * Lighthouse CLI). With no output path the summary is printed to stdout, which
 * is how the workflow feeds it into $GITHUB_STEP_SUMMARY and the report issue.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const reportsDir = process.argv[2];
const outPath = process.argv[3];

if (!reportsDir) {
  console.error("usage: node scripts/lighthouse-summary.mjs <reports-dir> [output.md]");
  process.exit(1);
}

const CATEGORY_ORDER = ["performance", "accessibility", "best-practices", "seo", "pwa"];

/** 0-1 score -> "🟢 92" / "🟠 74" / "🔴 41" / "—" for N/A. */
function badge(score) {
  if (score === null || score === undefined) return "—";
  const pct = Math.round(score * 100);
  const dot = pct >= 90 ? "🟢" : pct >= 50 ? "🟠" : "🔴";
  return `${dot} ${pct}`;
}

const files = readdirSync(reportsDir)
  .filter((f) => f.endsWith(".report.json"))
  .sort();

if (files.length === 0) {
  const msg = `No Lighthouse JSON reports found in \`${reportsDir}\`.`;
  if (outPath) writeFileSync(outPath, msg + "\n");
  else console.log(msg);
  process.exit(0);
}

const lines = [];
lines.push("## Lighthouse report");
lines.push("");
lines.push("<!-- generated by scripts/lighthouse-summary.mjs -->");
lines.push("");
lines.push(`Generated: ${new Date().toISOString()}`);
lines.push("");

const opportunitiesByUrl = [];

for (const file of files) {
  const lhr = JSON.parse(readFileSync(join(reportsDir, file), "utf8"));
  const url = lhr.finalDisplayedUrl || lhr.finalUrl || lhr.requestedUrl || file;
  const cats = lhr.categories || {};

  const present = CATEGORY_ORDER.filter((k) => cats[k]);
  lines.push(`### ${url}`);
  lines.push("");
  lines.push("| " + present.map((k) => cats[k].title).join(" | ") + " |");
  lines.push("| " + present.map(() => "---").join(" | ") + " |");
  lines.push(
    "| " + present.map((k) => badge(cats[k].score)).join(" | ") + " |"
  );
  lines.push("");

  // Top opportunities/diagnostics: failing audits with a real weight or a
  // measurable time saving, most impactful first.
  const audits = lhr.audits || {};
  const opps = Object.values(audits)
    .filter(
      (a) =>
        a.score !== null &&
        a.score < 0.9 &&
        (a.details?.type === "opportunity" ||
          a.scoreDisplayMode === "binary" ||
          a.scoreDisplayMode === "metricSavings")
    )
    .map((a) => {
      const metricSavings = Object.values(a.metricSavings || {}).filter(
        (n) => typeof n === "number"
      );
      const savingsMs =
        a.details?.overallSavingsMs ??
        (metricSavings.length ? Math.max(...metricSavings) : 0);
      return { title: a.title, savingsMs, displayValue: a.displayValue || "" };
    })
    .sort((a, b) => b.savingsMs - a.savingsMs)
    .slice(0, 8);

  if (opps.length) {
    opportunitiesByUrl.push({ url, opps });
  }
}

if (opportunitiesByUrl.length) {
  lines.push("### Top opportunities");
  lines.push("");
  for (const { url, opps } of opportunitiesByUrl) {
    lines.push(`**${url}**`);
    lines.push("");
    for (const o of opps) {
      const saving = o.savingsMs ? ` _(~${Math.round(o.savingsMs)} ms)_` : "";
      const dv = o.displayValue ? ` — ${o.displayValue}` : "";
      lines.push(`- ${o.title}${dv}${saving}`);
    }
    lines.push("");
  }
}

lines.push("### Требуемые правки");
lines.push("");
lines.push(
  "> Утром команда просматривает отчёт и отмечает здесь, что нужно поправить. " +
    "Перенесите принятые пункты в `docs/lighthouse/findings.md` и заведите задачи."
);
lines.push("");
lines.push("- [ ] _—_");
lines.push("");

const out = lines.join("\n");
if (outPath) writeFileSync(outPath, out + "\n");
else console.log(out);
